const actionTypes = {
  ADD_TODO: 'ADD_TODO',

  DEL_TODO: 'DEL_TODO',
  DEL_TODO_SAGA: 'DEL_TODO_SAGA',

  DONE_TODO: 'DONE_TODO',
  DONE_TODO_SAGA: 'DONE_TODO_SAGA',

  EDIT_TODO: 'EDIT_TODO',
  EDIT_TODO_SAGA: 'EDIT_TODO_SAGA',

  REF_TODO: 'REF_TODO',
  REF_TODO_SAGA: 'REF_TODO_SAGA',

  SIGNUP_AUTH: 'SIGNUP_AUTH',
  AUTH_SAGA: 'AUTH_SAGA',
  LOGIN_AUTH: 'LOGIN_AUTH',
  LOGIN_AUTH_SAGA: 'LOGIN_AUTH_SAGA',
  LOGOUT_AUTH: 'LOGOUT_AUTH',
  LOGOUT_AUTH_TODO: 'LOGOUT_AUTH_TODO',

  LOAD_START: 'LOAD_START',
  LOAD_END: 'LOAD_END',

  LOAD_START_MAIN: 'LOAD_START_MAIN',
  LOAD_END_MAIN: 'LOAD_END_MAIN',

  CHECK_AUTH: 'CHECK_AUTH',
  CHECK_AUTH_SAGA: 'CHECK_AUTH_SAGA',

  SEARCH_TODO: 'SEARCH_TODO',
  SEARCH_TODO_SAGA: 'SEARCH_TODO_SAGA',
};

export default actionTypes;
